version: '3.8'

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  csharp_compilator_service:
    image: csharp_compilator_service:latest
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  code_challanger_ui:
    image: code_challanger_ui:latest
    ports:
      - "8085:8085"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
